sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --rm=false -t docker.netbits.io:443/netbits/rr-qd-example-auth:latest .
      - docker push docker.netbits.io:443/netbits/rr-qd-example-auth:latest
